# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-20 07:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cap', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_collected', models.CharField(max_length=180)),
                ('feedback', models.TextField()),
                ('no_of_people', models.CharField(max_length=180)),
                ('platform', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cap.Platform')),
            ],
        ),
    ]
