# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-20 09:40
from __future__ import unicode_literals

import cap.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cap', '0002_platformdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180, unique=True)),
                ('description', models.TextField()),
                ('logo', models.ImageField(blank=True, null=True, upload_to=cap.models.get_image_path)),
                ('address', models.TextField()),
            ],
        ),
    ]
