# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-29 07:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cap', '0004_volunteers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='platform',
            name='organisations',
        ),
        migrations.AddField(
            model_name='platform',
            name='organisations',
            field=models.ManyToManyField(related_name='platform_orgs', to='cap.Organisation'),
        ),
    ]
