# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-29 09:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cap', '0005_auto_20151229_0756'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='orguser', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
