# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-29 11:45
from __future__ import unicode_literals

import cap.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cap', '0008_auto_20151229_1031'),
    ]

    operations = [
        migrations.AddField(
            model_name='platform',
            name='banner',
            field=models.ImageField(blank=True, upload_to=cap.models.get_image_path2),
        ),
    ]
