# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-30 06:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cap', '0009_platform_banner'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrgMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirmed', models.BooleanField(default=False)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='map_orgs', to='cap.Organisation')),
            ],
        ),
        migrations.CreateModel(
            name='PlatformMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirmed', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='platform',
            name='lat',
            field=models.CharField(max_length=180, null=True),
        ),
        migrations.AddField(
            model_name='platform',
            name='longt',
            field=models.CharField(max_length=180, null=True),
        ),
        migrations.AddField(
            model_name='platformmap',
            name='platform',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pmap_platform', to='cap.Platform'),
        ),
        migrations.AddField(
            model_name='platformmap',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pmap_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='orgmap',
            name='platform',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='map_platform', to='cap.Platform'),
        ),
    ]
