# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-19 08:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_auto_20151116_1057'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='mobile_id',
        ),
    ]
