# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-20 09:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_remove_userprofile_mobile_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='usertype',
            field=models.CharField(choices=[(b'Organisation', b'Organisation'), (b'CAP', b'CAP')], default=b'organisation', max_length=180),
        ),
    ]
