# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-21 15:24
from __future__ import unicode_literals

import authentication.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_userprofile_usertype'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='profilepicture',
            field=models.ImageField(blank=True, null=True, upload_to=authentication.models.get_image_path),
        ),
    ]
