# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-22 06:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_userprofile_profilepicture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='usertype',
            field=models.CharField(choices=[(b'Organisation', b'Organisation'), (b'CAP', b'CAP'), (b'Onestage', b'Onestage')], default=b'organisation', max_length=180),
        ),
    ]
