# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-22 06:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0010_auto_20151222_0629'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(max_length=180, null=True),
        ),
    ]
