# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-22 16:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0011_userprofile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='confirmationcode',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
