# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-22 16:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0012_auto_20151222_1612'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='confirmationcode',
        ),
    ]
