# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-24 06:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0013_remove_userprofile_confirmationcode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='confirmed',
        ),
    ]
