# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-30 06:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0015_auto_20151224_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='usertype',
            field=models.CharField(choices=[(b'Organisation', b'Organisation'), (b'CAP', b'CAP'), (b'Onestage', b'Onestage'), (b'CAP_member', b'CAP_member')], default=b'organisation', max_length=180),
        ),
    ]
